O = mod4_obj/
S = mod4_src/

LINK = f77 -O -o
COMPILE = f77 -O -c
EXECUTABLE = Mod4

$(EXECUTABLE):			  \
	$(O)Modtrn.o $(O)ab.o     \
	$(O)abcd.o   $(O)abcdta.o \
	$(O)aerext.o $(O)aermrg.o \
	$(O)aernsm.o $(O)aerprf.o \
	$(O)aertmp.o $(O)aitk.o   \
	$(O)albtrn.o $(O)altrin.o \
	$(O)aprfnu.o $(O)aruexa.o \
	$(O)asymtx.o $(O)atmcon.o \
	$(O)bbfn.o   $(O)betabs.o \
	$(O)bfh2o.o  $(O)bmcork.o \
	$(O)bmdata.o $(O)bmflux.o \
	$(O)bmload.o $(O)bmod.o   \
	$(O)bmtran.o $(O)bmxld.o  \
	$(O)bo2c.o   $(O)bo3hh0.o \
	$(O)bo3hh1.o $(O)bo3hh2.o \
	$(O)bs.o     $(O)c4d.o    \
	$(O)c4dta.o  $(O)c6dta.o  \
	$(O)check.o  $(O)chekin.o \
	$(O)chkres.o $(O)cirr18.o \
	$(O)cirrus.o $(O)ckd.o    \
	$(O)cldprf.o $(O)clddta.o \
	$(O)cmpint.o $(O)cnvphi.o \
	$(O)compar.o $(O)convrt.o \
	$(O)cool.o   $(O)cool0.o  \
	$(O)cossct.o $(O)cph2o.o  \
	$(O)cpo3.o   $(O)cptrcg.o \
	$(O)cpumix.o $(O)crdriv.o \
	$(O)crmerg.o $(O)crprof.o \
	$(O)crspec.o $(O)cruprf.o \
	$(O)cruspc.o $(O)cxdta.o  \
	$(O)dbltx.o  $(O)debye.o  \
	$(O)defalt.o $(O)del.o    \
	$(O)denlay.o $(O)desatt.o \
	$(O)devcbd.o $(O)dgrd.o   \
	$(O)disbbf.o $(O)disort.o \
	$(O)dop.o    $(O)dpandx.o \
	$(O)dpexnt.o $(O)dpfill.o \
	$(O)dpfish.o $(O)dpfnmn.o \
	$(O)dplayr.o $(O)dprarf.o \
	$(O)dprfpa.o $(O)dpscht.o \
	$(O)driver.o $(O)dstdta.o \
	$(O)errmsg.o $(O)exabin.o \
	$(O)expint.o $(O)extdta.o \
	$(O)fdbeta.o $(O)filter.o \
	$(O)filtsm.o $(O)flayz.o  \
	$(O)fluxes.o $(O)flxadd.o \
	$(O)flxsum.o $(O)flxtbl.o \
	$(O)fnames.o $(O)fndpth.o \
	$(O)frn296.o $(O)frq5dt.o \
	$(O)ftrang.o $(O)gamfog.o \
	$(O)geo.o    $(O)geoinp.o \
	$(O)gmrain.o $(O)gtstrt.o \
	$(O)h2src.o  $(O)hengns.o \
	$(O)hertda.o $(O)hno3.o   \
	$(O)indx.o   $(O)initcd.o \
	$(O)intcor.o $(O)interp.o \
	$(O)irfxn.o  $(O)isamax.o \
	$(O)jou.o    $(O)lay5dt.o \
	$(O)laycld.o $(O)layvsa.o \
	$(O)lenstr.o $(O)lepoly.o \
	$(O)locate.o $(O)loop.o   \
	$(O)mapms.o  $(O)mardta.o \
	$(O)marine.o $(O)mdta.o   \
	$(O)mlatmb.o $(O)molsct.o \
	$(O)msrad.o  $(O)mssolr.o \
	$(O)msthml.o $(O)newh2.o  \
	$(O)newsrc.o $(O)no2xs.o  \
	$(O)novaer.o $(O)novmrg.o \
	$(O)nunit.o  $(O)o2cont.o \
	$(O)o2int.o  $(O)o3chap.o \
	$(O)o3hht0.o $(O)o3hht1.o \
	$(O)o3hht2.o $(O)o3int.o  \
	$(O)o3uv.o   $(O)o3uvfd.o \
	$(O)openbm.o $(O)opnfl.o  \
	$(O)pf.o     $(O)phasef.o \
	$(O)phsdta.o $(O)plkavg.o \
	$(O)pravin.o $(O)prfdta.o \
	$(O)prtinp.o $(O)prtint.o \
	$(O)psi.o    $(O)psieca.o \
	$(O)pslct.o  $(O)qgausn.o \
	$(O)rain.o   $(O)random.o \
	$(O)ratio.o  $(O)rdcork.o \
	$(O)rdexa.o  $(O)rdnsm.o  \
	$(O)rdsun.o  $(O)reduce.o \
	$(O)rflect.o $(O)rfract.o \
	$(O)right.o  $(O)rmchan.o \
	$(O)rnscat.o $(O)rtbis.o  \
	$(O)sasum.o  $(O)saxpy.o  \
	$(O)schrun.o $(O)sclcol.o \
	$(O)scnflx.o $(O)sdot.o   \
	$(O)secsca.o $(O)setdis.o \
	$(O)setmtx.o $(O)sf260.o  \
	$(O)sf296.o  $(O)sgbco.o  \
	$(O)sgbfa.o  $(O)sgbsl.o  \
	$(O)sgeco.o  $(O)sgefa.o  \
	$(O)sgesl.o  $(O)shade.o  \
	$(O)shumg.o  $(O)sinsca.o \
	$(O)sint.o   $(O)slf260.o \
	$(O)slf296.o $(O)slftst.o \
	$(O)smgeo.o  $(O)smprep.o \
	$(O)sncms.o  $(O)so2xs.o  \
	$(O)soleig.o $(O)solve0.o \
	$(O)solve1.o $(O)solzen.o \
	$(O)source.o $(O)spaltr.o \
	$(O)spcflx.o $(O)sscal.o  \
	$(O)sscork.o $(O)ssgeo.o  \
	$(O)ssrad.o  $(O)stdmdl.o \
	$(O)subsol.o $(O)sunbd.o  \
	$(O)svsola.o $(O)tab.o    \
	$(O)tanht.o  $(O)terpev.o \
	$(O)terpso.o $(O)thmflx.o \
	$(O)title.o  $(O)tnrain.o \
	$(O)trans.o  $(O)trlay.o  \
	$(O)tstbad.o $(O)upbeam.o \
	$(O)upcase.o $(O)upisot.o \
	$(O)usrint.o $(O)vsa.o    \
	$(O)vsansm.o $(O)watvap.o \
	$(O)wrtbad.o $(O)wrtdim.o \
	$(O)wrtflt.o $(O)wtchan.o \
	$(O)wtcool.o $(O)wtlft.o  \
	$(O)wtrgt.o  $(O)wtsum.o  \
	$(O)wvbnrg.o $(O)xifunc.o \
	$(O)xmlatm.o $(O)zeroal.o \
	$(O)zeroit.o
	$(LINK) $(EXECUTABLE)     \
	$(O)Modtrn.o $(O)ab.o     \
	$(O)abcd.o   $(O)abcdta.o \
	$(O)aerext.o $(O)aermrg.o \
	$(O)aernsm.o $(O)aerprf.o \
	$(O)aertmp.o $(O)aitk.o   \
	$(O)albtrn.o $(O)altrin.o \
	$(O)aprfnu.o $(O)aruexa.o \
	$(O)asymtx.o $(O)atmcon.o \
	$(O)bbfn.o   $(O)betabs.o \
	$(O)bfh2o.o  $(O)bmcork.o \
	$(O)bmdata.o $(O)bmflux.o \
	$(O)bmload.o $(O)bmod.o   \
	$(O)bmtran.o $(O)bmxld.o  \
	$(O)bo2c.o   $(O)bo3hh0.o \
	$(O)bo3hh1.o $(O)bo3hh2.o \
	$(O)bs.o     $(O)c4d.o    \
	$(O)c4dta.o  $(O)c6dta.o  \
	$(O)check.o  $(O)chekin.o \
	$(O)chkres.o $(O)cirr18.o \
	$(O)cirrus.o $(O)ckd.o    \
	$(O)cldprf.o $(O)clddta.o \
	$(O)cmpint.o $(O)cnvphi.o \
	$(O)compar.o $(O)convrt.o \
	$(O)cool.o   $(O)cool0.o  \
	$(O)cossct.o $(O)cph2o.o  \
	$(O)cpo3.o   $(O)cptrcg.o \
	$(O)cpumix.o $(O)crdriv.o \
	$(O)crmerg.o $(O)crprof.o \
	$(O)crspec.o $(O)cruprf.o \
	$(O)cruspc.o $(O)cxdta.o  \
	$(O)dbltx.o  $(O)debye.o  \
	$(O)defalt.o $(O)del.o    \
	$(O)denlay.o $(O)desatt.o \
	$(O)devcbd.o $(O)dgrd.o   \
	$(O)disbbf.o $(O)disort.o \
	$(O)dop.o    $(O)dpandx.o \
	$(O)dpexnt.o $(O)dpfill.o \
	$(O)dpfish.o $(O)dpfnmn.o \
	$(O)dplayr.o $(O)dprarf.o \
	$(O)dprfpa.o $(O)dpscht.o \
	$(O)driver.o $(O)dstdta.o \
	$(O)errmsg.o $(O)exabin.o \
	$(O)expint.o $(O)extdta.o \
	$(O)fdbeta.o $(O)filter.o \
	$(O)filtsm.o $(O)flayz.o  \
	$(O)fluxes.o $(O)flxadd.o \
	$(O)flxsum.o $(O)flxtbl.o \
	$(O)fnames.o $(O)fndpth.o \
	$(O)frn296.o $(O)frq5dt.o \
	$(O)ftrang.o $(O)gamfog.o \
	$(O)geo.o    $(O)geoinp.o \
	$(O)gmrain.o $(O)gtstrt.o \
	$(O)h2src.o  $(O)hengns.o \
	$(O)hertda.o $(O)hno3.o   \
	$(O)indx.o   $(O)initcd.o \
	$(O)intcor.o $(O)interp.o \
	$(O)irfxn.o  $(O)isamax.o \
	$(O)jou.o    $(O)lay5dt.o \
	$(O)laycld.o $(O)layvsa.o \
	$(O)lenstr.o $(O)lepoly.o \
	$(O)locate.o $(O)loop.o   \
	$(O)mapms.o  $(O)mardta.o \
	$(O)marine.o $(O)mdta.o   \
	$(O)mlatmb.o $(O)molsct.o \
	$(O)msrad.o  $(O)mssolr.o \
	$(O)msthml.o $(O)newh2.o  \
	$(O)newsrc.o $(O)no2xs.o  \
	$(O)novaer.o $(O)novmrg.o \
	$(O)nunit.o  $(O)o2cont.o \
	$(O)o2int.o  $(O)o3chap.o \
	$(O)o3hht0.o $(O)o3hht1.o \
	$(O)o3hht2.o $(O)o3int.o  \
	$(O)o3uv.o   $(O)o3uvfd.o \
	$(O)openbm.o $(O)opnfl.o  \
	$(O)pf.o     $(O)phasef.o \
	$(O)phsdta.o $(O)plkavg.o \
	$(O)pravin.o $(O)prfdta.o \
	$(O)prtinp.o $(O)prtint.o \
	$(O)psi.o    $(O)psieca.o \
	$(O)pslct.o  $(O)qgausn.o \
	$(O)rain.o   $(O)random.o \
	$(O)ratio.o  $(O)rdcork.o \
	$(O)rdexa.o  $(O)rdnsm.o  \
	$(O)rdsun.o  $(O)reduce.o \
	$(O)rflect.o $(O)rfract.o \
	$(O)right.o  $(O)rmchan.o \
	$(O)rnscat.o $(O)rtbis.o  \
	$(O)sasum.o  $(O)saxpy.o  \
	$(O)schrun.o $(O)sclcol.o \
	$(O)scnflx.o $(O)sdot.o   \
	$(O)secsca.o $(O)setdis.o \
	$(O)setmtx.o $(O)sf260.o  \
	$(O)sf296.o  $(O)sgbco.o  \
	$(O)sgbfa.o  $(O)sgbsl.o  \
	$(O)sgeco.o  $(O)sgefa.o  \
	$(O)sgesl.o  $(O)shade.o  \
	$(O)shumg.o  $(O)sinsca.o \
	$(O)sint.o   $(O)slf260.o \
	$(O)slf296.o $(O)slftst.o \
	$(O)smgeo.o  $(O)smprep.o \
	$(O)sncms.o  $(O)so2xs.o  \
	$(O)soleig.o $(O)solve0.o \
	$(O)solve1.o $(O)solzen.o \
	$(O)source.o $(O)spaltr.o \
	$(O)spcflx.o $(O)sscal.o  \
	$(O)sscork.o $(O)ssgeo.o  \
	$(O)ssrad.o  $(O)stdmdl.o \
	$(O)subsol.o $(O)sunbd.o  \
	$(O)svsola.o $(O)tab.o    \
	$(O)tanht.o  $(O)terpev.o \
	$(O)terpso.o $(O)thmflx.o \
	$(O)title.o  $(O)tnrain.o \
	$(O)trans.o  $(O)trlay.o  \
	$(O)tstbad.o $(O)upbeam.o \
	$(O)upcase.o $(O)upisot.o \
	$(O)usrint.o $(O)vsa.o    \
	$(O)vsansm.o $(O)watvap.o \
	$(O)wrtbad.o $(O)wrtdim.o \
	$(O)wrtflt.o $(O)wtchan.o \
	$(O)wtcool.o $(O)wtlft.o  \
	$(O)wtrgt.o  $(O)wtsum.o  \
	$(O)wvbnrg.o $(O)xifunc.o \
	$(O)xmlatm.o $(O)zeroal.o \
	$(O)zeroit.o

$(O)Modtrn.o:   $(S)Modtrn.f
		$(COMPILE) $(S)Modtrn.f -o $(O)Modtrn.o

$(O)ab.o:	$(S)ab.f
		$(COMPILE) $(S)ab.f     -o $(O)ab.o

$(O)abcd.o:	$(S)abcd.f
		$(COMPILE) $(S)abcd.f   -o $(O)abcd.o

$(O)abcdta.o:   $(S)abcdta.f
		$(COMPILE) $(S)abcdta.f -o $(O)abcdta.o

$(O)aerext.o:   $(S)aerext.f $(S)PARAM.LST
		$(COMPILE) $(S)aerext.f -o $(O)aerext.o

$(O)aermrg.o:   $(S)aermrg.f $(S)PARAM.LST
		$(COMPILE) $(S)aermrg.f -o $(O)aermrg.o

$(O)aernsm.o:   $(S)aernsm.f $(S)PARAM.LST $(S)ERRORMOD.fi
		$(COMPILE) $(S)aernsm.f -o $(O)aernsm.o

$(O)aerprf.o:   $(S)aerprf.f
		$(COMPILE) $(S)aerprf.f -o $(O)aerprf.o

$(O)aertmp.o:   $(S)aertmp.f $(S)PARAM.LST
		$(COMPILE) $(S)aertmp.f -o $(O)aertmp.o

$(O)aitk.o:	$(S)aitk.f
		$(COMPILE) $(S)aitk.f   -o $(O)aitk.o

$(O)albtrn.o:   $(S)albtrn.f $(S)PARAM.LST $(S)ERRORMOD.fi
		$(COMPILE) $(S)albtrn.f -o $(O)albtrn.o

$(O)altrin.o:  	$(S)altrin.f
		$(COMPILE) $(S)altrin.f -o $(O)altrin.o

$(O)aprfnu.o:   $(S)aprfnu.f $(S)PARAM.LST $(S)ERRORMOD.fi
		$(COMPILE) $(S)aprfnu.f -o $(O)aprfnu.o

$(O)aruexa.o:   $(S)aruexa.f $(S)PARAM.LST $(S)ERRORMOD.fi
		$(COMPILE) $(S)aruexa.f -o $(O)aruexa.o

$(O)asymtx.o:  	$(S)asymtx.f
		$(COMPILE) $(S)asymtx.f -o $(O)asymtx.o

$(O)atmcon.o:  	$(S)atmcon.f
		$(COMPILE) $(S)atmcon.f -o $(O)atmcon.o

$(O)bbfn.o:	$(S)bbfn.f
		$(COMPILE) $(S)bbfn.f   -o $(O)bbfn.o

$(O)betabs.o:  	$(S)betabs.f $(S)ERRORMOD.fi
		$(COMPILE) $(S)betabs.f -o $(O)betabs.o

$(O)bfh2o.o:    $(S)bfh2o.f
		$(COMPILE) $(S)bfh2o.f  -o $(O)bfh2o.o

$(O)bmcork.o:   $(S)bmcork.f $(S)PARAM.LST $(S)ERRORMOD.fi
		$(COMPILE) $(S)bmcork.f -o $(O)bmcork.o

$(O)bmdata.o:   $(S)bmdata.f $(S)PARAM.LST
		$(COMPILE) $(S)bmdata.f -o $(O)bmdata.o

$(O)bmflux.o:   $(S)bmflux.f $(S)PARAM.LST $(S)ERRORMOD.fi
		$(COMPILE) $(S)bmflux.f -o $(O)bmflux.o

$(O)bmload.o:   $(S)bmload.f $(S)PARAM.LST
		$(COMPILE) $(S)bmload.f -o $(O)bmload.o

$(O)bmod.o:	$(S)bmod.f $(S)PARAM.LST
		$(COMPILE) $(S)bmod.f   -o $(O)bmod.o

$(O)bmtran.o:   $(S)bmtran.f $(S)PARAM.LST
		$(COMPILE) $(S)bmtran.f -o $(O)bmtran.o

$(O)bmxld.o:    $(S)bmxld.f $(S)PARAM.LST
		$(COMPILE) $(S)bmxld.f  -o $(O)bmxld.o

$(O)bo2c.o:	$(S)bo2c.f
		$(COMPILE) $(S)bo2c.f   -o $(O)bo2c.o

$(O)bo3hh0.o:	$(S)bo3hh0.f
		$(COMPILE) $(S)bo3hh0.f -o $(O)bo3hh0.o

$(O)bo3hh1.o:	$(S)bo3hh1.f
		$(COMPILE) $(S)bo3hh1.f -o $(O)bo3hh1.o

$(O)bo3hh2.o:	$(S)bo3hh2.f
		$(COMPILE) $(S)bo3hh2.f -o $(O)bo3hh2.o

$(O)bs.o:	$(S)bs.f
		$(COMPILE) $(S)bs.f     -o $(O)bs.o

$(O)c4d.o:	$(S)c4d.f
		$(COMPILE) $(S)c4d.f    -o $(O)c4d.o

$(O)c4dta.o:	$(S)c4dta.f
		$(COMPILE) $(S)c4dta.f  -o $(O)c4dta.o

$(O)c6dta.o:	$(S)c6dta.f
		$(COMPILE) $(S)c6dta.f  -o $(O)c6dta.o

$(O)check.o:	$(S)check.f $(S)ERRORMOD.fi
		$(COMPILE) $(S)check.f  -o $(O)check.o

$(O)chekin.o:	$(S)chekin.f
		$(COMPILE) $(S)chekin.f -o $(O)chekin.o

$(O)chkres.o:	$(S)chkres.f $(S)ERRORMOD.fi
		$(COMPILE) $(S)chkres.f -o $(O)chkres.o

$(O)cirr18.o:	$(S)cirr18.f $(S)PARAM.LST $(S)ERRORMOD.fi
		$(COMPILE) $(S)cirr18.f -o $(O)cirr18.o

$(O)cirrus.o:	$(S)cirrus.f $(S)PARAM.LST
		$(COMPILE) $(S)cirrus.f -o $(O)cirrus.o

$(O)ckd.o:	$(S)ckd.f
		$(COMPILE) $(S)ckd.f    -o $(O)ckd.o

$(O)clddta.o:	$(S)clddta.f $(S)PARAM.LST
		$(COMPILE) $(S)clddta.f -o $(O)clddta.o

$(O)cldprf.o:	$(S)cldprf.f
		$(COMPILE) $(S)cldprf.f -o $(O)cldprf.o

$(O)cmpint.o:	$(S)cmpint.f
		$(COMPILE) $(S)cmpint.f -o $(O)cmpint.o

$(O)cnvphi.o:	$(S)cnvphi.f $(S)ERRORMOD.fi
		$(COMPILE) $(S)cnvphi.f -o $(O)cnvphi.o

$(O)compar.o:	$(S)compar.f $(S)ERRORMOD.fi
		$(COMPILE) $(S)compar.f -o $(O)compar.o

$(O)convrt.o:	$(S)convrt.f $(S)PARAM.LST
		$(COMPILE) $(S)convrt.f -o $(O)convrt.o

$(O)cool.o:	$(S)cool.f $(S)PARAM.LST $(S)ERRORMOD.fi
		$(COMPILE) $(S)cool.f   -o $(O)cool.o

$(O)cool0.o:	$(S)cool0.f $(S)PARAM.LST $(S)ERRORMOD.fi
		$(COMPILE) $(S)cool0.f  -o $(O)cool0.o

$(O)cossct.o:	$(S)cossct.f
		$(COMPILE) $(S)cossct.f -o $(O)cossct.o

$(O)cph2o.o:	$(S)cph2o.f
		$(COMPILE) $(S)cph2o.f  -o $(O)cph2o.o

$(O)cpo3.o:	$(S)cpo3.f
		$(COMPILE) $(S)cpo3.f   -o $(O)cpo3.o

$(O)cptrcg.o:	$(S)cptrcg.f
		$(COMPILE) $(S)cptrcg.f -o $(O)cptrcg.o

$(O)cpumix.o:	$(S)cpumix.f
		$(COMPILE) $(S)cpumix.f -o $(O)cpumix.o

$(O)crdriv.o:	$(S)crdriv.f
		$(COMPILE) $(S)crdriv.f -o $(O)crdriv.o

$(O)crmerg.o:	$(S)crmerg.f $(S)PARAM.LST $(S)ERRORMOD.fi
		$(COMPILE) $(S)crmerg.f -o $(O)crmerg.o

$(O)crprof.o:	$(S)crprof.f $(S)PARAM.LST $(S)ERRORMOD.fi
		$(COMPILE) $(S)crprof.f -o $(O)crprof.o

$(O)crspec.o:	$(S)crspec.f $(S)PARAM.LST $(S)ERRORMOD.fi
		$(COMPILE) $(S)crspec.f -o $(O)crspec.o

$(O)cruprf.o:	$(S)cruprf.f $(S)PARAM.LST $(S)ERRORMOD.fi
		$(COMPILE) $(S)cruprf.f -o $(O)cruprf.o

$(O)cruspc.o:	$(S)cruspc.f $(S)PARAM.LST $(S)ERRORMOD.fi
		$(COMPILE) $(S)cruspc.f -o $(O)cruspc.o

$(O)cxdta.o:	$(S)cxdta.f
		$(COMPILE) $(S)cxdta.f  -o $(O)cxdta.o

$(O)dbltx.o:	$(S)dbltx.f
		$(COMPILE) $(S)dbltx.f  -o $(O)dbltx.o

$(O)debye.o:	$(S)debye.f
		$(COMPILE) $(S)debye.f  -o $(O)debye.o

$(O)defalt.o:	$(S)defalt.f $(S)PARAM.LST $(S)ERRORMOD.fi
		$(COMPILE) $(S)defalt.f -o $(O)defalt.o

$(O)del.o:	$(S)del.f
		$(COMPILE) $(S)del.f    -o $(O)del.o

$(O)denlay.o:	$(S)denlay.f
		$(COMPILE) $(S)denlay.f -o $(O)denlay.o

$(O)desatt.o:	$(S)desatt.f $(S)PARAM.LST $(S)ERRORMOD.fi
		$(COMPILE) $(S)desatt.f -o $(O)desatt.o

$(O)devcbd.o:	$(S)devcbd.f
		$(COMPILE) $(S)devcbd.f -o $(O)devcbd.o

$(O)dgrd.o:	$(S)dgrd.f
		$(COMPILE) $(S)dgrd.f   -o $(O)dgrd.o

$(O)disbbf.o:	$(S)disbbf.f
		$(COMPILE) $(S)disbbf.f -o $(O)disbbf.o

$(O)disort.o:	$(S)disort.f $(S)PARAM.LST
		$(COMPILE) $(S)disort.f -o $(O)disort.o

$(O)dop.o:	$(S)dop.f
		$(COMPILE) $(S)dop.f    -o $(O)dop.o

$(O)dpandx.o:	$(S)dpandx.f
		$(COMPILE) $(S)dpandx.f -o $(O)dpandx.o

$(O)dpexnt.o:	$(S)dpexnt.f
		$(COMPILE) $(S)dpexnt.f -o $(O)dpexnt.o

$(O)dpfill.o:	$(S)dpfill.f $(S)PARAM.LST $(S)ERRORMOD.fi
		$(COMPILE) $(S)dpfill.f -o $(O)dpfill.o

$(O)dpfish.o:	$(S)dpfish.f $(S)PARAM.LST
		$(COMPILE) $(S)dpfish.f -o $(O)dpfish.o

$(O)dpfnmn.o:	$(S)dpfnmn.f $(S)PARAM.LST $(S)ERRORMOD.fi
		$(COMPILE) $(S)dpfnmn.f -o $(O)dpfnmn.o

$(O)dplayr.o:	$(S)dplayr.f $(S)PARAM.LST
		$(COMPILE) $(S)dplayr.f -o $(O)dplayr.o

$(O)dprarf.o:	$(S)dprarf.f
		$(COMPILE) $(S)dprarf.f -o $(O)dprarf.o

$(O)dprfpa.o:	$(S)dprfpa.f $(S)PARAM.LST $(S)ERRORMOD.fi
		$(COMPILE) $(S)dprfpa.f -o $(O)dprfpa.o

$(O)dpscht.o:	$(S)dpscht.f
		$(COMPILE) $(S)dpscht.f -o $(O)dpscht.o

$(O)driver.o:	$(S)driver.f $(S)PARAM.LST $(S)ERRORMOD.fi $(S)JMASS.h
		$(COMPILE) $(S)driver.f -o $(O)driver.o

$(O)dstdta.o:	$(S)dstdta.f $(S)PARAM.LST
		$(COMPILE) $(S)dstdta.f -o $(O)dstdta.o

$(O)errmsg.o:	$(S)errmsg.f $(S)ERRORMOD.fi
		$(COMPILE) $(S)errmsg.f -o $(O)errmsg.o

$(O)exabin.o:	$(S)exabin.f $(S)PARAM.LST
		$(COMPILE) $(S)exabin.f -o $(O)exabin.o

$(O)expint.o:	$(S)expint.f
		$(COMPILE) $(S)expint.f -o $(O)expint.o

$(O)extdta.o:	$(S)extdta.f $(S)PARAM.LST
		$(COMPILE) $(S)extdta.f -o $(O)extdta.o

$(O)fdbeta.o:	$(S)fdbeta.f $(S)ERRORMOD.fi
		$(COMPILE) $(S)fdbeta.f -o $(O)fdbeta.o

$(O)filter.o:   $(S)filter.f $(S)PARAM.LST $(S)CHANNELS.h $(S)ERRORMOD.fi
		$(COMPILE) $(S)filter.f -o $(O)filter.o

$(O)filtsm.o:   $(S)filtsm.f $(S)CHANNELS.h
		$(COMPILE) $(S)filtsm.f -o $(O)filtsm.o

$(O)flayz.o:	$(S)flayz.f $(S)PARAM.LST $(S)ERRORMOD.fi
		$(COMPILE) $(S)flayz.f  -o $(O)flayz.o

$(O)fluxes.o:	$(S)fluxes.f $(S)ERRORMOD.fi
		$(COMPILE) $(S)fluxes.f -o $(O)fluxes.o

$(O)flxadd.o:	$(S)flxadd.f $(S)PARAM.LST $(S)ERRORMOD.fi
		$(COMPILE) $(S)flxadd.f -o $(O)flxadd.o

$(O)flxsum.o:	$(S)flxsum.f $(S)PARAM.LST $(S)ERRORMOD.fi
		$(COMPILE) $(S)flxsum.f -o $(O)flxsum.o

$(O)flxtbl.o:	$(S)flxtbl.f $(S)PARAM.LST $(S)ERRORMOD.fi
		$(COMPILE) $(S)flxtbl.f -o $(O)flxtbl.o

$(O)fnames.o:	$(S)fnames.f $(S)CHANNELS.h $(S)ERRORMOD.fi
		$(COMPILE) $(S)fnames.f -o $(O)fnames.o

$(O)fndpth.o:	$(S)fndpth.f $(S)ERRORMOD.fi
		$(COMPILE) $(S)fndpth.f -o $(O)fndpth.o

$(O)frn296.o:	$(S)frn296.f
		$(COMPILE) $(S)frn296.f -o $(O)frn296.o

$(O)frq5dt.o:	$(S)frq5dt.f
		$(COMPILE) $(S)frq5dt.f -o $(O)frq5dt.o

$(O)ftrang.o:	$(S)ftrang.f $(S)ERRORMOD.fi
		$(COMPILE) $(S)ftrang.f -o $(O)ftrang.o

$(O)gamfog.o:	$(S)gamfog.f
		$(COMPILE) $(S)gamfog.f -o $(O)gamfog.o

$(O)geo.o:	$(S)geo.f $(S)PARAM.LST $(S)ERRORMOD.fi
		$(COMPILE) $(S)geo.f    -o $(O)geo.o

$(O)geoinp.o:	$(S)geoinp.f $(S)ERRORMOD.fi
		$(COMPILE) $(S)geoinp.f -o $(O)geoinp.o

$(O)gmrain.o:	$(S)gmrain.f
		$(COMPILE) $(S)gmrain.f -o $(O)gmrain.o

$(O)gtstrt.o:	$(S)gtstrt.f
		$(COMPILE) $(S)gtstrt.f -o $(O)gtstrt.o

$(O)h2src.o:	$(S)h2src.f $(S)ERRORMOD.fi
		$(COMPILE) $(S)h2src.f  -o $(O)h2src.o

$(O)hengns.o:	$(S)hengns.f
		$(COMPILE) $(S)hengns.f -o $(O)hengns.o

$(O)hertda.o:	$(S)hertda.f
		$(COMPILE) $(S)hertda.f -o $(O)hertda.o

$(O)hno3.o:	$(S)hno3.f
		$(COMPILE) $(S)hno3.f   -o $(O)hno3.o

$(O)indx.o:	$(S)indx.f
		$(COMPILE) $(S)indx.f   -o $(O)indx.o

$(O)initcd.o:	$(S)initcd.f $(S)PARAM.LST
		$(COMPILE) $(S)initcd.f -o $(O)initcd.o

$(O)intcor.o:	$(S)intcor.f
		$(COMPILE) $(S)intcor.f -o $(O)intcor.o

$(O)interp.o:	$(S)interp.f
		$(COMPILE) $(S)interp.f -o $(O)interp.o

$(O)irfxn.o:	$(S)irfxn.f $(S)PARAM.LST
		$(COMPILE) $(S)irfxn.f  -o $(O)irfxn.o

$(O)isamax.o:	$(S)isamax.f
		$(COMPILE) $(S)isamax.f -o $(O)isamax.o

$(O)jou.o:	$(S)jou.f $(S)ERRORMOD.fi
		$(COMPILE) $(S)jou.f    -o $(O)jou.o

$(O)lay5dt.o:	$(S)lay5dt.f $(S)PARAM.LST
		$(COMPILE) $(S)lay5dt.f -o $(O)lay5dt.o

$(O)laycld.o:	$(S)laycld.f $(S)PARAM.LST
		$(COMPILE) $(S)laycld.f -o $(O)laycld.o

$(O)layvsa.o:	$(S)layvsa.f $(S)PARAM.LST
		$(COMPILE) $(S)layvsa.f -o $(O)layvsa.o

$(O)lenstr.o:	$(S)lenstr.f
		$(COMPILE) $(S)lenstr.f -o $(O)lenstr.o

$(O)lepoly.o:	$(S)lepoly.f
		$(COMPILE) $(S)lepoly.f -o $(O)lepoly.o

$(O)locate.o:	$(S)locate.f
		$(COMPILE) $(S)locate.f -o $(O)locate.o

$(O)loop.o:	$(S)loop.f $(S)PARAM.LST $(S)ERRORMOD.fi
		$(COMPILE) $(S)loop.f   -o $(O)loop.o

$(O)mapms.o:	$(S)mapms.f $(S)PARAM.LST $(S)ERRORMOD.fi
		$(COMPILE) $(S)mapms.f  -o $(O)mapms.o

$(O)mardta.o:	$(S)mardta.f
		$(COMPILE) $(S)mardta.f -o $(O)mardta.o

$(O)marine.o:	$(S)marine.f $(S)PARAM.LST $(S)ERRORMOD.fi
		$(COMPILE) $(S)marine.f -o $(O)marine.o

$(O)mdta.o:	$(S)mdta.f $(S)PARAM.LST
		$(COMPILE) $(S)mdta.f   -o $(O)mdta.o

$(O)mlatmb.o:	$(S)mlatmb.f
		$(COMPILE) $(S)mlatmb.f -o $(O)mlatmb.o

$(O)molsct.o:	$(S)molsct.f
		$(COMPILE) $(S)molsct.f -o $(O)molsct.o

$(O)msrad.o:	$(S)msrad.f $(S)PARAM.LST
		$(COMPILE) $(S)msrad.f  -o $(O)msrad.o

$(O)mssolr.o:	$(S)mssolr.f
		$(COMPILE) $(S)mssolr.f -o $(O)mssolr.o

$(O)msthml.o:	$(S)msthml.f
		$(COMPILE) $(S)msthml.f -o $(O)msthml.o

$(O)newh2.o:	$(S)newh2.f
		$(COMPILE) $(S)newh2.f  -o $(O)newh2.o

$(O)newsrc.o:	$(S)newsrc.f $(S)PARAM.LST $(S)ERRORMOD.fi
		$(COMPILE) $(S)newsrc.f -o $(O)newsrc.o

$(O)no2xs.o:	$(S)no2xs.f
		$(COMPILE) $(S)no2xs.f  -o $(O)no2xs.o

$(O)novaer.o:	$(S)novaer.f $(S)PARAM.LST $(S)ERRORMOD.fi
		$(COMPILE) $(S)novaer.f -o $(O)novaer.o

$(O)novmrg.o:	$(S)novmrg.f $(S)PARAM.LST $(S)ERRORMOD.fi
		$(COMPILE) $(S)novmrg.f -o $(O)novmrg.o

$(O)nunit.o:	$(S)nunit.f $(S)ERRORMOD.fi
		$(COMPILE) $(S)nunit.f  -o $(O)nunit.o

$(O)o2cont.o:	$(S)o2cont.f
		$(COMPILE) $(S)o2cont.f -o $(O)o2cont.o

$(O)o2int.o:	$(S)o2int.f
		$(COMPILE) $(S)o2int.f  -o $(O)o2int.o

$(O)o3chap.o:	$(S)o3chap.f
		$(COMPILE) $(S)o3chap.f -o $(O)o3chap.o

$(O)o3hht0.o:	$(S)o3hht0.f
		$(COMPILE) $(S)o3hht0.f -o $(O)o3hht0.o

$(O)o3hht1.o:	$(S)o3hht1.f
		$(COMPILE) $(S)o3hht1.f -o $(O)o3hht1.o

$(O)o3hht2.o:	$(S)o3hht2.f
		$(COMPILE) $(S)o3hht2.f -o $(O)o3hht2.o

$(O)o3int.o:	$(S)o3int.f
		$(COMPILE) $(S)o3int.f  -o $(O)o3int.o

$(O)o3uv.o:	$(S)o3uv.f
		$(COMPILE) $(S)o3uv.f   -o $(O)o3uv.o

$(O)o3uvfd.o:	$(S)o3uvfd.f
		$(COMPILE) $(S)o3uvfd.f -o $(O)o3uvfd.o

$(O)openbm.o:	$(S)openbm.f $(S)PARAM.LST $(S)ERRORMOD.fi
		$(COMPILE) $(S)openbm.f -o $(O)openbm.o

$(O)opnfl.o:	$(S)opnfl.f $(S)ERRORMOD.fi
		$(COMPILE) $(S)opnfl.f  -o $(O)opnfl.o

$(O)pf.o:	$(S)pf.f
		$(COMPILE) $(S)pf.f     -o $(O)pf.o

$(O)phasef.o:	$(S)phasef.f $(S)PARAM.LST $(S)ERRORMOD.fi
		$(COMPILE) $(S)phasef.f -o $(O)phasef.o

$(O)phsdta.o:	$(S)phsdta.f
		$(COMPILE) $(S)phsdta.f -o $(O)phsdta.o

$(O)plkavg.o:	$(S)plkavg.f
		$(COMPILE) $(S)plkavg.f -o $(O)plkavg.o

$(O)pravin.o:	$(S)pravin.f $(S)ERRORMOD.fi
		$(COMPILE) $(S)pravin.f -o $(O)pravin.o

$(O)prfdta.o:	$(S)prfdta.f
		$(COMPILE) $(S)prfdta.f -o $(O)prfdta.o

$(O)prtinp.o:	$(S)prtinp.f $(S)ERRORMOD.fi
		$(COMPILE) $(S)prtinp.f -o $(O)prtinp.o

$(O)prtint.o:	$(S)prtint.f $(S)ERRORMOD.fi
		$(COMPILE) $(S)prtint.f -o $(O)prtint.o

$(O)psi.o:	$(S)psi.f
		$(COMPILE) $(S)psi.f    -o $(O)psi.o

$(O)psieca.o:	$(S)psieca.f
		$(COMPILE) $(S)psieca.f -o $(O)psieca.o

$(O)pslct.o:	$(S)pslct.f
		$(COMPILE) $(S)pslct.f  -o $(O)pslct.o

$(O)qgausn.o:	$(S)qgausn.f
		$(COMPILE) $(S)qgausn.f -o $(O)qgausn.o

$(O)rain.o:	$(S)rain.f $(S)PARAM.LST
		$(COMPILE) $(S)rain.f   -o $(O)rain.o

$(O)random.o:	$(S)random.f
		$(COMPILE) $(S)random.f -o $(O)random.o

$(O)ratio.o:	$(S)ratio.f
		$(COMPILE) $(S)ratio.f  -o $(O)ratio.o

$(O)rdcork.o:	$(S)rdcork.f $(S)PARAM.LST $(S)ERRORMOD.fi
		$(COMPILE) $(S)rdcork.f -o $(O)rdcork.o

$(O)rdexa.o:	$(S)rdexa.f $(S)PARAM.LST $(S)ERRORMOD.fi
		$(COMPILE) $(S)rdexa.f  -o $(O)rdexa.o

$(O)rdnsm.o:	$(S)rdnsm.f $(S)ERRORMOD.fi
		$(COMPILE) $(S)rdnsm.f  -o $(O)rdnsm.o

$(O)rdsun.o:	$(S)rdsun.f $(S)ERRORMOD.fi
		$(COMPILE) $(S)rdsun.f  -o $(O)rdsun.o

$(O)reduce.o:	$(S)reduce.f $(S)ERRORMOD.fi
		$(COMPILE) $(S)reduce.f -o $(O)reduce.o

$(O)rflect.o:	$(S)rflect.f $(S)PARAM.LST $(S)ERRORMOD.fi
		$(COMPILE) $(S)rflect.f -o $(O)rflect.o

$(O)rfract.o:   $(S)rfract.f
		$(COMPILE) $(S)rfract.f -o $(O)rfract.o

$(O)right.o:    $(S)right.f
		$(COMPILE) $(S)right.f  -o $(O)right.o

$(O)rmchan.o:   $(S)rmchan.f $(S)CHANNELS.h
		$(COMPILE) $(S)rmchan.f -o $(O)rmchan.o

$(O)rnscat.o:	$(S)rnscat.f
		$(COMPILE) $(S)rnscat.f -o $(O)rnscat.o

$(O)rtbis.o:	$(S)rtbis.f $(S)ERRORMOD.fi
		$(COMPILE) $(S)rtbis.f  -o $(O)rtbis.o

$(O)sasum.o:	$(S)sasum.f
		$(COMPILE) $(S)sasum.f  -o $(O)sasum.o

$(O)saxpy.o:	$(S)saxpy.f
		$(COMPILE) $(S)saxpy.f  -o $(O)saxpy.o

$(O)schrun.o:	$(S)schrun.f
		$(COMPILE) $(S)schrun.f -o $(O)schrun.o

$(O)sclcol.o:	$(S)sclcol.f $(S)PARAM.LST $(S)ERRORMOD.fi
		$(COMPILE) $(S)sclcol.f -o $(O)sclcol.o

$(O)scnflx.o:	$(S)scnflx.f $(S)PARAM.LST
		$(COMPILE) $(S)scnflx.f -o $(O)scnflx.o

$(O)sdot.o:	$(S)sdot.f
		$(COMPILE) $(S)sdot.f   -o $(O)sdot.o

$(O)secsca.o:	$(S)secsca.f
		$(COMPILE) $(S)secsca.f -o $(O)secsca.o

$(O)setdis.o:	$(S)setdis.f
		$(COMPILE) $(S)setdis.f -o $(O)setdis.o

$(O)setmtx.o:	$(S)setmtx.f
		$(COMPILE) $(S)setmtx.f -o $(O)setmtx.o

$(O)sf260.o:	$(S)sf260.f
		$(COMPILE) $(S)sf260.f  -o $(O)sf260.o

$(O)sf296.o:	$(S)sf296.f
		$(COMPILE) $(S)sf296.f  -o $(O)sf296.o

$(O)sgbco.o:	$(S)sgbco.f
		$(COMPILE) $(S)sgbco.f  -o $(O)sgbco.o

$(O)sgbfa.o:	$(S)sgbfa.f
		$(COMPILE) $(S)sgbfa.f  -o $(O)sgbfa.o

$(O)sgbsl.o:	$(S)sgbsl.f
		$(COMPILE) $(S)sgbsl.f  -o $(O)sgbsl.o

$(O)sgeco.o:	$(S)sgeco.f
		$(COMPILE) $(S)sgeco.f  -o $(O)sgeco.o

$(O)sgefa.o:	$(S)sgefa.f
		$(COMPILE) $(S)sgefa.f  -o $(O)sgefa.o

$(O)sgesl.o:	$(S)sgesl.f
		$(COMPILE) $(S)sgesl.f  -o $(O)sgesl.o

$(O)shade.o:	$(S)shade.f $(S)PARAM.LST
		$(COMPILE) $(S)shade.f  -o $(O)shade.o

$(O)shumg.o:	$(S)shumg.f
		$(COMPILE) $(S)shumg.f  -o $(O)shumg.o

$(O)sinsca.o:	$(S)sinsca.f
		$(COMPILE) $(S)sinsca.f -o $(O)sinsca.o

$(O)sint.o:	$(S)sint.f
		$(COMPILE) $(S)sint.f   -o $(O)sint.o

$(O)slf260.o:	$(S)slf260.f
		$(COMPILE) $(S)slf260.f -o $(O)slf260.o

$(O)slf296.o:	$(S)slf296.f
		$(COMPILE) $(S)slf296.f -o $(O)slf296.o

$(O)slftst.o:	$(S)slftst.f
		$(COMPILE) $(S)slftst.f -o $(O)slftst.o

$(O)smgeo.o:	$(S)smgeo.f
		$(COMPILE) $(S)smgeo.f  -o $(O)smgeo.o

$(O)smprep.o:	$(S)smprep.f $(S)ERRORMOD.fi
		$(COMPILE) $(S)smprep.f -o $(O)smprep.o

$(O)sncms.o:	$(S)sncms.f
		$(COMPILE) $(S)sncms.f  -o $(O)sncms.o

$(O)so2xs.o:	$(S)so2xs.f
		$(COMPILE) $(S)so2xs.f  -o $(O)so2xs.o

$(O)soleig.o:	$(S)soleig.f $(S)ERRORMOD.fi
		$(COMPILE) $(S)soleig.f -o $(O)soleig.o

$(O)solve0.o:	$(S)solve0.f
		$(COMPILE) $(S)solve0.f -o $(O)solve0.o

$(O)solve1.o:	$(S)solve1.f
		$(COMPILE) $(S)solve1.f -o $(O)solve1.o

$(O)solzen.o:	$(S)solzen.f $(S)PARAM.LST
		$(COMPILE) $(S)solzen.f -o $(O)solzen.o

$(O)source.o:	$(S)source.f $(S)ERRORMOD.fi
		$(COMPILE) $(S)source.f -o $(O)source.o

$(O)spaltr.o:	$(S)spaltr.f
		$(COMPILE) $(S)spaltr.f -o $(O)spaltr.o

$(O)spcflx.o:	$(S)spcflx.f $(S)PARAM.LST $(S)ERRORMOD.fi
		$(COMPILE) $(S)spcflx.f -o $(O)spcflx.o

$(O)sscal.o:	$(S)sscal.f
		$(COMPILE) $(S)sscal.f  -o $(O)sscal.o

$(O)sscork.o:	$(S)sscork.f $(S)PARAM.LST
		$(COMPILE) $(S)sscork.f -o $(O)sscork.o

$(O)ssgeo.o:	$(S)ssgeo.f $(S)PARAM.LST $(S)ERRORMOD.fi
		$(COMPILE) $(S)ssgeo.f  -o $(O)ssgeo.o

$(O)ssrad.o:	$(S)ssrad.f $(S)PARAM.LST $(S)ERRORMOD.fi
		$(COMPILE) $(S)ssrad.f  -o $(O)ssrad.o

$(O)stdmdl.o:	$(S)stdmdl.f $(S)PARAM.LST $(S)ERRORMOD.fi
		$(COMPILE) $(S)stdmdl.f -o $(O)stdmdl.o

$(O)subsol.o:	$(S)subsol.f $(S)ERRORMOD.fi
		$(COMPILE) $(S)subsol.f -o $(O)subsol.o

$(O)sunbd.o:	$(S)sunbd.f
		$(COMPILE) $(S)sunbd.f  -o $(O)sunbd.o

$(O)svsola.o:	$(S)svsola.f
		$(COMPILE) $(S)svsola.f -o $(O)svsola.o

$(O)tab.o:	$(S)tab.f
		$(COMPILE) $(S)tab.f    -o $(O)tab.o

$(O)tanht.o:	$(S)tanht.f $(S)PARAM.LST
		$(COMPILE) $(S)tanht.f  -o $(O)tanht.o

$(O)terpev.o:	$(S)terpev.f
		$(COMPILE) $(S)terpev.f -o $(O)terpev.o

$(O)terpso.o:	$(S)terpso.f
		$(COMPILE) $(S)terpso.f -o $(O)terpso.o

$(O)thmflx.o:	$(S)thmflx.f $(S)PARAM.LST
		$(COMPILE) $(S)thmflx.f -o $(O)thmflx.o

$(O)title.o:	$(S)title.f
		$(COMPILE) $(S)title.f  -o $(O)title.o

$(O)tnrain.o:	$(S)tnrain.f
		$(COMPILE) $(S)tnrain.f -o $(O)tnrain.o

$(O)trans.o:	$(S)trans.f $(S)PARAM.LST $(S)ERRORMOD.fi $(S)JMASS.h
		$(COMPILE) $(S)trans.f  -o $(O)trans.o

$(O)trlay.o:	$(S)trlay.f
		$(COMPILE) $(S)trlay.f  -o $(O)trlay.o

$(O)tstbad.o:	$(S)tstbad.f
		$(COMPILE) $(S)tstbad.f -o $(O)tstbad.o

$(O)upbeam.o:	$(S)upbeam.f
		$(COMPILE) $(S)upbeam.f -o $(O)upbeam.o

$(O)upcase.o:	$(S)upcase.f
		$(COMPILE) $(S)upcase.f -o $(O)upcase.o

$(O)upisot.o:	$(S)upisot.f
		$(COMPILE) $(S)upisot.f -o $(O)upisot.o

$(O)usrint.o:	$(S)usrint.f
		$(COMPILE) $(S)usrint.f -o $(O)usrint.o

$(O)vsa.o:	$(S)vsa.f $(S)ERRORMOD.fi
		$(COMPILE) $(S)vsa.f    -o $(O)vsa.o

$(O)vsansm.o:	$(S)vsansm.f $(S)PARAM.LST
		$(COMPILE) $(S)vsansm.f -o $(O)vsansm.o

$(O)watvap.o:	$(S)watvap.f $(S)ERRORMOD.fi
		$(COMPILE) $(S)watvap.f -o $(O)watvap.o

$(O)wrtbad.o:	$(S)wrtbad.f
		$(COMPILE) $(S)wrtbad.f -o $(O)wrtbad.o

$(O)wrtdim.o:	$(S)wrtdim.f
		$(COMPILE) $(S)wrtdim.f -o $(O)wrtdim.o

$(O)wrtflt.o:   $(S)wrtflt.f $(S)CHANNELS.h $(S)ERRORMOD.fi
		$(COMPILE) $(S)wrtflt.f -o $(O)wrtflt.o

$(O)wtchan.o:   $(S)wtchan.f $(S)PARAM.LST $(S)CHANNELS.h
		$(COMPILE) $(S)wtchan.f -o $(O)wtchan.o

$(O)wtcool.o:	$(S)wtcool.f $(S)PARAM.LST $(S)ERRORMOD.fi
		$(COMPILE) $(S)wtcool.f -o $(O)wtcool.o

$(O)wtlft.o:	$(S)wtlft.f
		$(COMPILE) $(S)wtlft.f  -o $(O)wtlft.o

$(O)wtrgt.o:	$(S)wtrgt.f
		$(COMPILE) $(S)wtrgt.f  -o $(O)wtrgt.o

$(O)wtsum.o:	$(S)wtsum.f $(S)PARAM.LST $(S)ERRORMOD.fi
		$(COMPILE) $(S)wtsum.f  -o $(O)wtsum.o

$(O)wvbnrg.o:	$(S)wvbnrg.f
		$(COMPILE) $(S)wvbnrg.f -o $(O)wvbnrg.o

$(O)xifunc.o:	$(S)xifunc.f
		$(COMPILE) $(S)xifunc.f -o $(O)xifunc.o

$(O)xmlatm.o:	$(S)xmlatm.f $(S)PARAM.LST
		$(COMPILE) $(S)xmlatm.f -o $(O)xmlatm.o

$(O)zeroal.o:	$(S)zeroal.f
		$(COMPILE) $(S)zeroal.f -o $(O)zeroal.o

$(O)zeroit.o:	$(S)zeroit.f
		$(COMPILE) $(S)zeroit.f -o $(O)zeroit.o
